export const DIFF_COLLAPSED = 'DIFF_COLLAPSED';
export const DIFF_CONDITION_DELETED = 'DIFF_CONDITION_DELETED';
export const DIFF_CONDITION_ADDED = 'DIFF_CONDITION_ADDED';
export const DIFF_CONDITION_UPDATED = 'DIFF_CONDITION_UPDATED';
export const EXTERNAL_NAVIGATION_REQUESTED = 'EXTERNAL_NAVIGATION_REQUESTED';
export const EXTENSION_UI_LOADED = 'EXTENSION_UI_LOADED';